option(
  'link_mode',
  type: 'combo',
  choices: ['shared', 'static'],
  value: 'shared',
  description: 'How optional external dependencies are linked'
)

option(
  'tests',
  type: 'feature',
  value: 'enabled',
  description: 'Build the libpkgaudit test suite'
)

option(
  'tools',
  type: 'feature',
  value: 'disabled',
  description: 'Build reference command-line tools'
)

option(
  'install_tools',
  type: 'boolean',
  value: false,
  description: 'Install reference command-line tools'
)

option(
  'manpages',
  type: 'feature',
  value: 'auto',
  description: 'Build and install manual pages'
)
